# This is meant to set up additional software for Framework laptops running Fedora 35

- hosts: localhost
  tasks:

# Power Management
    - name: Install Powertop
      become: yes
      package:
        name: powertop
        state: present
    - name: Install TLP
      become: yes
      package:
        name: tlp
        state: present
    - name: Remove GNOME power-profiles-daemon
      become: yes
      package:
        name: power-profiles-daemon
        state: absent
# sudo systemctl enable tlp.service
# sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket
# sudo tlp start

# Improve s2idle suspend battery life:
# sudo grubby --update-kernel=ALL --args=nvme.noacpi=1
    - name: Set kernel flags to allow NVME SSDs to sleep properly
      become: yes
      command: grubby --update-kernel=ALL --args=nvme.noacpi=1

# Allow s2idle/modern standby to work on Fedora 35:
# THIS IS WRONG! as having "" breaks the file. FIX IT!
# Can be undone with sudo grubby --update-kernel=ALL --remove-args='"acpi_osi=!Windows 2020"'
# sudo grubby --update-kernel=ALL --args='acpi_osi=!Windows 2020'
    # - name: Set kernel flags to remove change that broke s2idle
    #   become: yes
    #   command: grubby --update-kernel=ALL --args='acpi_osi=!Windows 2020'

# For battery thresholds with TLP: https://old.reddit.com/r/thinkpad/comments/og5anr/til_battery_charging_thresholds_best_practices/


# Fractional Scaling
# gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
# Turn off with gsettings reset org.gnome.mutter experimental-features
# This makes VSCodium look blurry

# Audio Jack Mic-In
# Create file '/etc/modprobe.d/alsa-base.conf'
# Add 'options snd-hda-intel model=dell-headset-multi' to it
# Reboot


# Tiger Lake iGPU Hardware Acceleration:
# intel-media-driver is needed for Tiger Lake and newer
    - name: Install Intel Iris XE Driver
      become: yes
      package:
        name: intel-media-driver
        state: present
    - name: Install Intel GPU Tools
      become: yes
      package:
        name: igt-gpu-tools
        state: present

# VAAPI for Fedora 35:
    - name: Install libva utilities
      become: yes
      package:
        name: libva-utils
        state: present
    - name: Install ffmpeg
      become: yes
      package:
        name: ffmpeg
        state: present

# If you have the Tempo audio codec Framework mainboard, you need to disable it to achieve PC10 residency:
# sudo su
# echo 9 | sudo tee /sys/kernel/debug/pmc_core/ltr_ignore
# Unofortunately, this doesn't work on Fedora 35 with Secure Boot enabled. Not sure why
