# This is meant to set up additional software for Framework laptops running Fedora 35
# TLP installation guide: https://linrunner.de/tlp/installation/fedora.html

- hosts: localhost
  tasks:

# Power Management
    - name: Install Powertop
      become: yes
      package:
        name: powertop
        state: present
    - name: Install TLP
      become: yes
      package:
        name: tlp
        state: present
    - name: Remove GNOME power-profiles-daemon
      become: yes
      package:
        name: power-profiles-daemon
        state: absent

# sudo systemctl enable tlp.service
    - name: Enable TLP service
      ansible.builtin.systemd:
        name: tlp.service
        enabled: yes
# sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket
# Test that these actually work!!
    - name: Stop service systemd-rfkill.service and ensure it is masked
      ansible.builtin.systemd:
        name: systemd-rfkill.service
        enabled: no
        state: stopped
        masked: yes
    - name: Stop service systemd-rfkill.socket and ensure it is masked
      ansible.builtin.systemd:
        name: systemd-rfkill.socket
        enabled: no
        state: stopped
        masked: yes
# sudo tlp start
    - name: Manually start TLP
      become: yes
      command: tlp start


# WARNING: Do not use update kernel all with grubby for untested args!. update an older entry and test it first!!!
# If it breaks, in grub press e to edit your boot entry and remove whatever you added.
# Improve s2idle suspend battery life:
# sudo grubby --update-kernel=ALL --args=nvme.noacpi=1
    - name: Set kernel flags to allow NVME SSDs to sleep properly
      become: yes
      command: grubby --update-kernel=ALL --args=nvme.noacpi=1

# Allow s2idle/modern standby to work on Fedora 35:
# sudo grubby --update-kernel=ALL --args='"acpi_osi=!Windows 2020"'
# To remove: sudo grubby --update-kernel=ALL --remove-args='"acpi_osi=!Windows 2020"'
# If grubby reports that it cant find the command, just delete from /etc/default/grub and it should be removed
    - name: Set kernel flags to remove change that broke s2idle
      become: yes
      command: grubby --update-kernel=ALL --args='"acpi_osi=!Windows 2020"'
# These grubby commands will edit /etc/default/grub.
# Check current cmdline args with: cat /proc/cmdline

# Fractional Scaling
# gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
# Turn off with gsettings reset org.gnome.mutter experimental-features
# This makes VSCodium look blurry
# VSCodium Fix:
# Edit /usr/share/applications/codium.desktop
# Add '--enable-features=UseOzonePlatform --ozone-platform=wayland' after codium and before the existing args

# HiDPI
# Just make tweaks set font scale factor to 0.9
# gsettings set org.gnome.desktop.interface text-scaling-factor 0.9


# Audio Jack Mic-In
# Create file '/etc/modprobe.d/alsa-base.conf'
# Add 'options snd-hda-intel model=dell-headset-multi' to it
# Only needed for realtek codec mainboard
# Will mess up Tempo boards
# Maybe make a way to check?
# https://community.frame.work/t/ubuntu-21-10-tiger-lake-sound/11908/12
    # - name: Create ALSA config file to enable Mic-In via headphone jack
    #   become: yes
    #   copy:
    #     dest: /etc/modprobe.d/alsa-base.conf
    #     content: options snd-hda-intel model=dell-headset-multi
# Reboot for changes to take effect!

# Tiger Lake iGPU Hardware Acceleration:
# intel-media-driver is needed for Tiger Lake and newer
    - name: Install Intel Iris XE Driver
      become: yes
      package:
        name: intel-media-driver
        state: present
    - name: Install Intel GPU Tools
      become: yes
      package:
        name: igt-gpu-tools
        state: present

# VAAPI for Fedora 35:
    - name: Install libva utilities
      become: yes
      package:
        name: libva-utils
        state: present
    - name: Install ffmpeg
      become: yes
      package:
        name: ffmpeg
        state: present

# Firefox config:
# Could use https://ncona.com/2019/10/how-to-configure-firefox-programmatically/
# But we'll use an Ansible module here
  vars:
    firefox:
      prefs:
        - name: media.ffmpeg.vaapi.enabled
          value: true

# If you have the Tempo audio codec Framework mainboard, you need to disable it to achieve PC10 residency:
# sudo su
# echo 9 | sudo tee /sys/kernel/debug/pmc_core/ltr_ignore
# Unofortunately, this doesn't work on Fedora 35 with Secure Boot enabled. Not sure why
